GantSign Development Containers
===============================
:toc:
:toc-placement: preamble
:showtitle:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This project contains Docker container images that provide a command line
development environment for use with
https://code.visualstudio.com/docs/remote/containers[VS Code].

== Prerequisites

If your don't want to see the occasional garbled character, you'll need to
install a couple of fonts and set your terminal emulator to use the Nerd Font.

* A https://www.nerdfonts.com[Nerd Font] installed and enabled in your terminal
* An emoji font e.g.
+
.Debian/Ubuntu
[source,bash]
----
sudo apt install fonts-noto-color-emoji
----
+
.RedHat/Amazon
[source,bash]
----
sudo dnf install google-noto-emoji-fonts
----

== Base container

The base container is the smallest container for development that doesn't
require Docker or Kubernetes.

=== Features

In addition to basic GNU/Linux command line tools this container contains the
following:

* https://github.com/sharkdp/bat[bat] a `cat` alternative with syntax highlighting
* https://github.com/aristocratos/btop[btop] a color `top` alternative with broader information
* https://github.com/dandavison/delta[Delta] for more readable diffs
* https://github.com/muesli/duf[duf] a `df` alternative with easier to read output
* https://github.com/bootandy/dust[Dust] a `du` alternative with easier to read output
* https://github.com/sharkdp/fd[fd] an easier to use `find` alternative
* https://github.com/junegunn/fzf[fzf] a general-purpose command-line fuzzy finder
* https://github.com/Aloxaf/fzf-tab[fzf-tab] use `fzf` for tab-completion
* https://github.com/garabik/grc[Generic Colouriser] add color output to many basic GNU/Linux commands
* https://github.com/cli/cli[GitHub CLI] to make GitHub easier to work with from the command line
* https://github.com/nicolargo/glances[Glances] a color `top` alternative with broader information
* https://github.com/sharkdp/hexyl[hexyl] hex viewer
* https://htop.dev[htop] a color `top` alternative
* https://httpie.io[HTTPie] easier to use `curl` alternative with color output
* https://github.com/httpie/http-prompt[HTTP Prompt] interactive interface to HTTPie
* https://github.com/Orange-OpenSource/hurl[Hurl] for testing REST APIs
* https://github.com/sharkdp/hyperfine[hyperfine] benchmarking tool
* https://github.com/jesseduffield/lazygit[lazygit] a terminal UI for git commands
* https://github.com/Peltoche/lsd[LSD (LSDeluxe)] a `ls`/`tree` alternative with color and icons
* https://github.com/nvm-sh/nvm[Node Version Manager] for installing/managing versions of Node.js
* https://stedolan.github.io/jq/[jq] for manipulating JSON
* https://ohmyz.sh[Oh My Zsh] for tab-completion and aliases
* https://github.com/pypa/pipenv[Pipenv] for managing Python dependencies/virtualenvs
* https://github.com/pypa/pipx[pipx] for installing Python applications
* https://github.com/dalance/procs[procs] a `ps` alternative with color and keyword search
* https://github.com/BurntSushi/ripgrep[ripgrep] for searching files/directories for text
* https://github.com/chmln/sd[sd] easy to use `sed` alternative
* https://sdkman.io[SDKMAN!] for installing/managing SDKs such as Java and Maven
* https://github.com/vaporup/ssh-tools[ssh-tools] command line utilities for SSH
* https://starship.rs[starship] a full featured shell prompt
* https://github.com/ggreer/the_silver_searcher[The Silver Searcher] for searching files/directories for text
* https://github.com/XAMPPRocky/tokei[Tokei] view stats about your code
* https://github.com/vim-airline/vim-airline[vim-airline] status/tabline for vim
* https://github.com/MichaelAquilina/zsh-you-should-use[You Should Use] to remind you of available shell aliases
* https://github.com/ajeetdsouza/zoxide[zoxide] easily navigate to previous directories
* https://github.com/zimfw/zimfw[zimfw] for managing Zsh plugins (including Oh My Zsh)
* https://github.com/zsh-users/zsh-autosuggestions[zsh-autosuggestions] suggests commands as you type based on history and completions
* https://github.com/zsh-users/zsh-syntax-highlighting[zsh-syntax-highlighting] syntax highlighting for the command line

=== Running standalone

If you just want to try it out, you can run it standalone:

[source,bash]
----
docker run --rm -ti ghcr.io/gantsign/devcontainer-base
----

=== Running in VS Code

First you need to create a `.devcontainer/devcontainer.json` file in the root
of your project:

..devcontainer/devcontainer.json
[source,js]
----
// For format details, see https://aka.ms/devcontainer.json
{
	"name": "GantSign",
	"build": {
		"dockerfile": "Dockerfile",
	},

	"settings": {
		"editor.renderWhitespace": "all",
		"editor.rulers": [
			80,
			100,
			120
		],
		"editor.guides.bracketPairs": true
	},

	"extensions": [
		"streetsidesoftware.code-spell-checker",
		"editorconfig.editorconfig"
	],

	"forwardPorts": [],

	"mounts": [
		"source=devcontainer-history,target=/home/dev/.shell_history,type=volume",
		"source=devcontainer-zoxide,target=/home/dev/.local/share/zoxide,type=volume"
	],

	"runArgs": [
		// [Optional] Uncomment for improved security, requires https://github.com/nestybox/sysbox to be installed
		// "--runtime=sysbox-runc"
	],

	"remoteUser": "dev",
}
----

Then you need to create a Dockerfile:

..devcontainer/Dockerfile
[source,Dockerfile]
----
FROM ghcr.io/gantsign/devcontainer-base

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# ** [Optional] Uncomment this section to install SDKs. **
# SHELL [ "/usr/bin/bash", "--login", "-c" ]
# RUN sdk_install java 11
# RUN sdk_install maven 3
# RUN nvm install --lts
----

Then press `Ctrl-P` and select "Remote-Containers: Open Folder in Container..."
from the menu.

== DinD container

For when you need to use Docker for development. The DinD container contains
everything in the base container as well as Docker-in-Docker and related tools.

=== Features

In addition to the tools in the base container the DinD container also contains
the following:

* https://ctop.sh[ctop] a `top` like tool for containers
* https://github.com/wagoodman/dive[dive] a tool for exploring Docker images
* https://www.docker.com[Docker] the most well know container tool
* https://docs.docker.com/compose/[Docker Compose] a tool for defining and running multi-container Docker applications
* https://github.com/jesseduffield/lazydocker[Lazydocker] a simple terminal UI for Docker & Docker Compose

=== Running in VS Code

First you need to create a `.devcontainer/devcontainer.json` file in the root
of your project:

..devcontainer/devcontainer.json
[source,js]
----
// For format details, see https://aka.ms/devcontainer.json
{
	"name": "GantSign",
	"build": {
		"dockerfile": "Dockerfile",
	},

	"settings": {
		"editor.renderWhitespace": "all",
		"editor.rulers": [
			80,
			100,
			120
		],
		"editor.guides.bracketPairs": true
	},

	"extensions": [
		"streetsidesoftware.code-spell-checker",
		"editorconfig.editorconfig"
	],

	"forwardPorts": [],

	"mounts": [
		"source=devcontainer-history,target=/home/dev/.shell_history,type=volume",
		"source=devcontainer-zoxide,target=/home/dev/.local/share/zoxide,type=volume",
		// To preserve Docker images between runs
		"source=devcontainer-docker,target=/var/lib/docker,type=volume"
	],

	"runArgs": [
		// Requires https://github.com/nestybox/sysbox to be installed
		"--runtime=sysbox-runc"
	],

	"remoteUser": "dev",

	// So the Docker init script runs
	"overrideCommand": false
}
----

[NOTE]
====
For Docker-in-Docker to work, it either needs to be run with
https://github.com/nestybox/sysbox[sysbox] `--runtime=sysbox-runc` (which you
need to install on your host machine) or with the `--privileged` flag. See
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ for
why you should avoid the `--privileged` flag.
====

Then you need to create a Dockerfile:

..devcontainer/Dockerfile
[source,Dockerfile]
----
FROM ghcr.io/gantsign/devcontainer-dind

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# ** [Optional] Uncomment this section to install SDKs. **
# SHELL [ "/usr/bin/bash", "--login", "-c" ]
# RUN sdk_install java 11
# RUN sdk_install maven 3
# RUN nvm install --lts
----

Then press `Ctrl-P` and select "Remote-Containers: Open Folder in Container..."
from the menu.

== K8s container

For when you need to use Kubernetes for development. The K8s container contains
everything in the DinD container as well as K3s and related tools.

=== Features

In addition to the tools in the DinD container the K3s container also contains
the following:

* https://helm.sh[Helm] Kubernetes package manager
* https://k3s.io[K3s] lightweight Kubernetes distribution
* https://k9scli.io[k9s] terminal UI for Kubernetes
* https://github.com/ahmetb/kubectx/[kubectx] for switching between Kubernetes contexts
* https://github.com/ahmetb/kubectx/[kubens] for switching between Kubernetes namespaces
* https://kustomize.io[Kustomize] for customizing application configuration
* https://github.com/stern/stern[stern] allows you to `tail` multiple pods
* https://www.telepresence.io[Telepresence] bridge between local dev and your Kubernetes cluster

=== Running in VS Code

First you need to create a `.devcontainer/devcontainer.json` file in the root
of your project:

..devcontainer/devcontainer.json
[source,js]
----
// For format details, see https://aka.ms/devcontainer.json
{
	"name": "GantSign",
	"build": {
		"dockerfile": "Dockerfile",
	},

	"settings": {
		"editor.renderWhitespace": "all",
		"editor.rulers": [
			80,
			100,
			120
		],
		"editor.guides.bracketPairs": true
	},

	"extensions": [
		"streetsidesoftware.code-spell-checker",
		"editorconfig.editorconfig"
	],

	"forwardPorts": [],

	"mounts": [
		"source=devcontainer-history,target=/home/dev/.shell_history,type=volume",
		"source=devcontainer-zoxide,target=/home/dev/.local/share/zoxide,type=volume",
		// To preserve Docker images between runs
		"source=devcontainer-docker,target=/var/lib/docker,type=volume"
	],

	"runArgs": [
		// Requires https://github.com/nestybox/sysbox to be installed
		"--runtime=sysbox-runc"
		// To use Telepresence you need to use --privileged instead of Sysbox
		// "--privileged"
	],

	"remoteUser": "dev",

	// So the Docker & K3s init script runs
	"overrideCommand": false
}
----

[NOTE]
====
For Docker-in-Docker or K3s to work, they either needs to be run with
https://github.com/nestybox/sysbox[sysbox] `--runtime=sysbox-runc` (which you
need to install on your host machine) or with the `--privileged` flag. See
https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ for
why you should avoid the `--privileged` flag.
====

[IMPORTANT]
====
For Telepresence to work you need to run the container with the `--privileged`
flag instead of Sysbox.
====

Then you need to create a Dockerfile:

..devcontainer/Dockerfile
[source,Dockerfile]
----
FROM ghcr.io/gantsign/devcontainer-k8s

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# ** [Optional] Uncomment this section to install SDKs. **
# SHELL [ "/usr/bin/bash", "--login", "-c" ]
# RUN sdk_install java 11
# RUN sdk_install maven 3
# RUN nvm install --lts

# ** [Optional] Uncomment this section if you don't want to run K3s on start. **
# ENTRYPOINT ["/usr/local/share/docker-init.sh"]
# CMD ["sleep", "infinity"]
----

Then press `Ctrl-P` and select "Remote-Containers: Open Folder in Container..."
from the menu.

== License

This project uses the Unlicense but the resulting container images contain
software under various different open-source licenses.

== Author information

John Freeman

GantSign Ltd.
Company No. 06109112 (registered in England)
