FROM ghcr.io/gantsign/devcontainer-k8s

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# ** [Optional] Uncomment this section to install SDKs. **
# SHELL [ "/usr/bin/bash", "--login", "-c" ]
# RUN sdk_install java 11
# RUN sdk_install maven 3
# RUN nvm install --lts
